services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn water_palnt.wsgi:application
    autoDeploy: true
