# Generated by Django 5.2 on 2025-04-27 08:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('id_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('Solar', 'سولار'), ('gasoline', 'بنزين'), ('oil', 'زيت')], default='gasoline', max_length=10)),
                ('type', models.CharField(choices=[('in', 'وارد'), ('out', 'صادر')], max_length=10)),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('price_per_liter', models.FloatField()),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField()),
                ('date', models.CharField()),
                ('car_count', models.IntegerField()),
                ('fuel_in', models.FloatField()),
                ('fuel_out', models.FloatField()),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('assistant', models.CharField(max_length=255)),
                ('car_count', models.PositiveIntegerField()),
                ('documented_count', models.PositiveIntegerField()),
                ('documented_for', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=300)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(default='123456', max_length=100)),
                ('id_number', models.CharField(max_length=9)),
                ('job', models.CharField(choices=[('مدير', 'مدير'), ('موظف', 'موظف'), ('سائق', 'سائق')], default='موظف', max_length=100)),
                ('start_date', models.CharField()),
                ('salary', models.FloatField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.worker')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
