# Generated by Django 5.2 on 2025-04-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='password',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user_name',
        ),
    ]
