# Generated by Django 5.2 on 2025-04-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_worker_password_remove_worker_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrecords',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
