# Generated by Django 5.2 on 2025-04-29 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_carrecords_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.mainitem')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.device')),
                ('main_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.mainitem')),
                ('maintenance_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.maintenancelocation')),
                ('sub_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.subitem')),
            ],
        ),
    ]
