# Generated by Django 5.2 on 2025-04-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_device_mainitem_maintenancelocation_subitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subitem',
            name='main_item',
        ),
        migrations.AlterField(
            model_name='mainitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.device'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='main_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.mainitem'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.maintenancelocation'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='sub_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.subitem'),
        ),
        migrations.AlterField(
            model_name='maintenancelocation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
