# Generated by Django 5.2 on 2025-04-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_subitem_main_item_alter_mainitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='start_date',
            field=models.DateField(),
        ),
    ]
