# Generated by Django 5.2 on 2025-04-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_expenses_type_palce_expenses_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='job',
            field=models.CharField(blank=True, choices=[('مشرف', 'مشرف'), ('موظف', 'موظف'), ('مساعد', 'مساعد')], default='موظف', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.FloatField(blank=True, default=500, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
