# Generated by Django 5.2 on 2025-05-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_worker_id_number_alter_worker_job_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Palce_Expenses',
            new_name='Place_Expenses',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AlterField(
            model_name='driver',
            name='id_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
