# Generated by Django 5.2 on 2025-05-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_rename_palce_expenses_place_expenses_delete_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrecords',
            name='documented_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrecords',
            name='documented_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
