# Generated by Django 5.2 on 2025-05-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_carrecords_documented_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fueltransaction',
            name='price_per_liter',
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='fuel_transaction_source',
            field=models.CharField(choices=[('خاص', 'خاص'), ('بلدية', 'بلدية'), ('أخرى', 'أخرى')], default='خاص', max_length=13),
        ),
        migrations.AlterField(
            model_name='carrecords',
            name='notes',
            field=models.CharField(blank=True, default='لا يوجد', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='fuel_type',
            field=models.CharField(choices=[('Solar', 'سولار'), ('gasoline', 'بنزين'), ('oil', 'زيت')], default='gasoline', max_length=13),
        ),
    ]
