# Generated by Django 5.2 on 2025-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_fueltransaction_price_per_liter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/workers/'),
        ),
    ]
