# Generated by Django 5.2 on 2025-05-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_worker_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='image',
            new_name='worker_image',
        ),
    ]
