# Generated by Django 5.2 on 2025-05-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_rename_image_worker_worker_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FountainRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('Liters', models.PositiveIntegerField()),
                ('car_count', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, default='لا يوجد', max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_image',
            field=models.ImageField(blank=True, null=True, upload_to='workers/'),
        ),
    ]
