# Generated by Django 5.2 on 2025-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_fountainrecords_alter_worker_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fountainrecords',
            name='car_count',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
