# Generated by Django 5.2 on 2025-05-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_fountainrecords_car_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fountainrecords',
            name='Liters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fountainrecords',
            name='car_count',
            field=models.PositiveIntegerField(),
        ),
    ]
