# Generated by Django 5.2 on 2025-05-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_fountainrecords_liters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fountainrecords',
            name='Liters',
        ),
    ]
