# Generated by Django 5.2 on 2025-05-31 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_remove_fountainrecords_liters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='worker_image',
        ),
    ]
