# Generated by Django 5.2 on 2026-07-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_alter_driver_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='carrecords',
            name='cups',
            field=models.IntegerField(default=0, verbose_name='عدد الأكواب'),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.driver', verbose_name='اسم السائق'),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='meter_reading',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='القراءة'),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('motor', 'ماتور'), ('vehicle', 'سيارة')], max_length=20, null=True, verbose_name='الجهة'),
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع السيارة'),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='fuel_type',
            field=models.CharField(choices=[('Solar', 'سولار'), ('gasoline', 'بنزين'), ('oil', 'زيت')], default='Solar', max_length=13),
        ),
        migrations.CreateModel(
            name='VehicleFuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fuel_quantity', models.FloatField(verbose_name='كمية السولار')),
                ('odometer_before', models.PositiveIntegerField(verbose_name='قراءة العداد قبل')),
                ('odometer_after', models.PositiveIntegerField(verbose_name='قراءة العداد بعد')),
                ('notes', models.CharField(blank=True, default='لا يوجد', max_length=300, null=True, verbose_name='ملاحظات')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.driver', verbose_name='اسم السائق')),
            ],
        ),
    ]
